server.port: 9000
our.very.very.very.secret.key: secret
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/spring-security-fundamentals
    password: root
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update